# Generated by Django 3.1.7 on 2021-03-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='data',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('WITHDRAW', 'Withdraw')], max_length=10),
        ),
    ]
